server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;	

        add_header 'Access-Control-Allow-Origin' 'psgc.gitlab.io';
        add_header 'Access-Control-Allow-Origin' 'geolocation-db.com';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,Authorization,X-Requested-With,If-Modified-Since,Keep-Alive,User-Agent,Cache-Control,Content-Type';
        add_header 'Access-Control-Allow-Credentials' 'true';
    }

    location /happy-play-api/ {
        proxy_pass http://happy-play-api:80;

        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        
        # Optional: Allow headers for things like Authorization tokens
        add_header 'Access-Control-Allow-Headers' 'DNT,Authorization,X-Requested-With,If-Modified-Since,Keep-Alive,User-Agent,Cache-Control,Content-Type';

        # Optional: Allow credentials
        add_header 'Access-Control-Allow-Credentials' 'true';
    }
    
    location /happy-play-support/ {
        proxy_pass http://happy-play-support:80;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';

        # Optional: Allow headers for things like Authorization tokens
        add_header 'Access-Control-Allow-Headers' 'DNT,Authorization,X-Requested-With,If-Modified-Since,Keep-Alive,User-Agent,Cache-Control,Content-Type';

        # Optional: Allow credentials
        add_header 'Access-Control-Allow-Credentials' 'true';
    }


    location /auth.esatpt.com/ {
        proxy_pass http://auth.esatpt.com;
        
        # Add CORS headers
        add_header 'Access-Control-Allow-Origin' 'auth.esatpt.com';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        
        # Optional: Allow headers for things like Authorization tokens
        add_header 'Access-Control-Allow-Headers' 'DNT,Authorization,X-Requested-With,If-Modified-Since,Keep-Alive,User-Agent,Cache-Control,Content-Type';

        # Optional: Allow credentials
        add_header 'Access-Control-Allow-Credentials' 'true';
    }
    
    location /api-core-bingo.esatpt.com/ {
        proxy_pass http://api-core-bingo.esatpt.com;

        # Add CORS headers
        add_header 'Access-Control-Allow-Origin' 'api-core-bingo.esatpt.com';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';

        # Optional: Allow headers for things like Authorization tokens
        add_header 'Access-Control-Allow-Headers' 'DNT,Authorization,X-Requested-With,If-Modified-Since,Keep-Alive,User-Agent,Cache-Control,Content-Type';

        # Optional: Allow credentials
        add_header 'Access-Control-Allow-Credentials' 'true';
    }
}
