export const ConstArrayExt = {
    getIDTypes: () => {
        return [
            "Passport",
            "(SSS) Social Security System",
            "(GSIS) Government Service Insurance System",
            "(UMID) Unified Multi-Purpose Identification",
            "(LTO) Drivers License",
            "(PRC) Professional Regulatory Commission",
            "(OWWA) Overseas Workers Welfare Administration",
            "(PNP) Philippine National Police",
            "Airman License",
            "Postal ID",
            "Seafarers Record Book",
            "Senior Citizen",
            "PWD",
            "Solo Parent",
            "School ID",
            "Others"
        ];
    },
    getBloodTypes: () => {
        return ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" ];
    },
    getCivilStatuses: () => {
        return ["Single", "Married", "Widowed", "Divorced"];
    },
    getNatureOfWorkList: () => {
        return [
            "Lawyer",
            "Dentist",
            "Engineer",
            "SelfEmployed",
            "Employee private Sector",
            "Professional",
            "Other Professional",
            "Unemployed",
            "Retired",
            "Home duties",
            "Student",
            "Business/Entrepreneur",
            "Doctor",
            "Athlete",
            "Housewife",
            "Managers",
            "Technicians and associate professionals",
            "Clerical support workers",
            "Service and sales workers",
            "Skilled agricultural, forestry and fishery workers",
            "Craft and related trades workers",
            "Plant and machine operators and assemblers",
            "Elementary occupations  (unskilled workers)",
            "Armed forces occupation",
        ];
    },
    getSourceOfIncomeList: () => {
        return [
            "Student Allowance - Domestic/Local",
            "Spouse Allowance - Domestic/Local",
            "Salary - Domestic/Local",
            "Commission",
            "Pension - Domestic/Local",
            "Retired",
            "Retirement - Domestic/Local",
            "Business - Domestic/Local",
            "Allotment/Remittance - Local",
            "Salary - Abroad/Offshore",
            "Student Allowance - Abroad/Offshore",
            "Pension - Abroad/Offshore",
            "Retirement - Abroad/Offshore",
            "Business - Abroad/Offshore",
            "Allotment/Remittance - Abroad",
            "Proceeds from Sale of Property",
            "Proceeds from Lottery",
            "Proceeds from Loan",
            "Donations",
        ];
    },
    getNationalityList: () => {
        return [
            "Afghan",
            "Albanian",
            "Algerian",
            "American",
            "Andorran",
            "Angolan",
            "Antiguans",
            "Argentinean",
            "Armenian",
            "Australian",
            "Austrian",
            "Azerbaijani",
            "Bahamian",
            "Bahraini",
            "Bangladeshi",
            "Barbadian",
            "Barbudans",
            "Batswana",
            "Belarusian",
            "Belgian",
            "Belizean",
            "Beninese",
            "Bhutanese",
            "Bolivian",
            "Bosnian",
            "Brazilian",
            "British",
            "Bruneian",
            "Bulgarian",
            "Burkinabe",
            "Burmese",
            "Burundian",
            "Cambodian",
            "Cameroonian",
            "Canadian",
            "Cape Verdean",
            "Central African",
            "Chadian",
            "Chilean",
            "Chinese",
            "Colombian",
            "Comoran",
            "Congolese",
            "Costa Rican",
            "Croatian",
            "Cuban",
            "Cypriot",
            "Czech",
            "Danish",
            "Djibouti",
            "Dominican",
            "Dutch",
            "East Timorese",
            "Ecuadorean",
            "Egyptian",
            "Emirian",
            "Equatorial Guinean",
            "Eritrean",
            "Estonian",
            "Ethiopian",
            "Fijian",
            "Filipino",
            "Finnish",
            "French",
            "Gabonese",
            "Gambian",
            "Georgian",
            "German",
            "Ghanaian",
            "Greek",
            "Grenadian",
            "Guatemalan",
            "Guinea-Bissauan",
            "Guinean",
            "Guyanese",
            "Haitian",
            "Herzegovinian",
            "Honduran",
            "Hungarian",
            "I-Kiribati",
            "Icelander",
            "Indian",
            "Indonesian",
            "Iranian",
            "Iraqi",
            "Irish",
            "Israeli",
            "Italian",
            "Ivorian",
            "Jamaican",
            "Japanese",
            "Jordanian",
            "Kazakhstani",
            "Kenyan",
            "Kittian and Nevisian",
            "Kuwaiti",
            "Kyrgyz",
            "Laotian",
            "Latvian",
            "Lebanese",
            "Liberian",
            "Libyan",
            "Liechtensteiner",
            "Lithuanian",
            "Luxembourger",
            "Macedonian",
            "Malagasy",
            "Malawian",
            "Malaysian",
            "Maldivan",
            "Malian",
            "Maltese",
            "Marshallese",
            "Mauritanian",
            "Mauritian",
            "Mexican",
            "Micronesian",
            "Moldovan",
            "Monacan",
            "Mongolian",
            "Moroccan",
            "Mosotho",
            "Motswana",
            "Mozambican",
            "Namibian",
            "Nauruan",
            "Nepalese",
            "New Zealander",
            "Nicaraguan",
            "Nigerian",
            "Nigerien",
            "North Korean",
            "Northern Irish",
            "Norwegian",
            "Omani",
            "Pakistani",
            "Palauan",
            "Panamanian",
            "Papua New Guinean",
            "Paraguayan",
            "Peruvian",
            "Polish",
            "Portuguese",
            "Qatari",
            "Romanian",
            "Russian",
            "Rwandan",
            "Saint Lucian",
            "Salvadoran",
            "Samoan",
            "San Marinese",
            "Sao Tomean",
            "Saudi",
            "Scottish",
            "Senegalese",
            "Serbian",
            "Seychellois",
            "Sierra Leonean",
            "Singaporean",
            "Slovakian",
            "Slovenian",
            "Solomon Islander",
            "Somali",
            "South African",
            "South Korean",
            "Spanish",
            "Sri Lankan",
            "Sudanese",
            "Surinamer",
            "Swazi",
            "Swedish",
            "Swiss",
            "Syrian",
            "Taiwanese",
            "Tajik",
            "Tanzanian",
            "Thai",
            "Togolese",
            "Tongan",
            "Trinidadian or Tobagonian",
            "Tunisian",
            "Turkish",
            "Tuvaluan",
            "Ugandan",
            "Ukrainian",
            "Uruguayan",
            "Uzbekistani",
            "Venezuelan",
            "Vietnamese",
            "Welsh",
            "Yemenite",
            "Zambian",
            "Zimbabwean"
        ];
    }
}